org: abponcio
app: open-ai-api
service: open-ai-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage,'dev'}
  region: ap-south-1
  timeout: 28
  environment:
    OPEN_AI_SECRET_KEY: ${param:OPEN_AI_SECRET_KEY}
  httpApi:
    cors: true

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

  quiz:
    handler: handler.generateQuiz
    events:
      - httpApi:
          path: /generate-quiz
          method: post

  generateRecipes:
    handler: handler.generateRecipes
    events:
      - httpApi:
          path: /generate-recipes
          method: get


plugins:
  - serverless-plugin-typescript
